#ifndef __APP_CONFIG_H__
#define __APP_CONFIG_H__
#ifdef __cplusplus
extern "C"
{
#endif
#include "WtBuild.h"
/*版本配置*/
#define APP_CONFIG_VERSION_MAJOR 1               // 主要版本号，大改动功能。0 to 255。
#define APP_CONFIG_VERSION_MINOR 0               // 次要版本号，新增功能。0 to 255。
#define APP_CONFIG_VERSION_REVISION 0            // 修订版本号，修订功能。0 to 255。
#define APP_CONFIG_VERSION_BUILD WT_BUILD_NUMBER // 构建版本号，编译次数。 0 to 255。

/*产品名称(单选)*/
#define APP_CONFIG_PRODUCT_NAME_FL500 1
#define APP_CONFIG_PRODUCT_NAME_FL600 2
#define APP_CONFIG_PRODUCT_NAME_CURRENT APP_CONFIG_PRODUCT_NAME_FL500

/*客户名称(单选)*/
#define APP_CONFIG_CUSTOMER_NAME_QTK 1
#define APP_CONFIG_CUSTOMER_NAME_ELC 2
#define APP_CONFIG_CUSTOMER_NAME_CURRENT APP_CONFIG_CUSTOMER_NAME_QTK

/*产品特性功能(多选，至少选一个)*/
#define APP_CONFIG_FUNCTION_NAME_NET 0x01
#define APP_CONFIG_FUNCTION_NAME_BT 0x02
#define APP_CONFIG_FUNCTION_NAME_CURRENT APP_CONFIG_FUNCTION_NAME_NET | APP_CONFIG_FUNCTION_NAME_BT

/*产品协议(多选，至少选一个)*/
#define APP_CONFIG_PROTOCOL_NAME_PT 0x01
#define APP_CONFIG_PROTOCOL_NAME_JT808 0x02
#define APP_CONFIG_PROTOCOL_NAME_CURRENT APP_CONFIG_PROTOCOL_NAME_PT | APP_CONFIG_PROTOCOL_NAME_JT808
#ifdef __cplusplus
}
#endif
#endif
