#ifndef __APP_CONFIG_H__
#define __APP_CONFIG_H__
/*版本配置*/
#define APP_CONFIG_VERSION_MAJOR 1    // 主要版本号(0 to 255)。
#define APP_CONFIG_VERSION_MINOR 0    // 次要版本号(0 to 255)。
#define APP_CONFIG_VERSION_REVISION 1 // 修订版本号(0 to 255)。
#define APP_CONFIG_VERSION_BUILD 99   // 构建版本号(0 to 255)。

/*产品名称(单选)*/
#define APP_CONFIG_PRODUCT_NAME_FL500 1
#define APP_CONFIG_PRODUCT_NAME_FL600 2
#define APP_CONFIG_PRODUCT_NAME_CURRENT APP_CONFIG_PRODUCT_NAME_FL500

/*客户名称(单选)*/
#define APP_CONFIG_CUSTOMER_NAME_QTK 1
#define APP_CONFIG_CUSTOMER_NAME_ELC 2
#define APP_CONFIG_CUSTOMER_NAME_MOBI 3
#define APP_CONFIG_CUSTOMER_NAME_CURRENT APP_CONFIG_CUSTOMER_NAME_MOBI

/*产品功能特性(单选)*/
#define APP_CONFIG_FUNCTION_NAME_GENERAL 1
#define APP_CONFIG_FUNCTION_NAME_NET 2
#define APP_CONFIG_FUNCTION_NAME_BT 3
#define APP_CONFIG_FUNCTION_NAME_CURRENT APP_CONFIG_FUNCTION_NAME_GENERAL

/*产品协议(多选)*/
#define APP_CONFIG_PROTOCOL_NAME_PT100 0x0001u
#define APP_CONFIG_PROTOCOL_NAME_JT808 0x0002u
#define APP_CONFIG_PROTOCOL_NAME_NONE 0u
#define APP_CONFIG_PROTOCOL_NAME_ALL (APP_CONFIG_PROTOCOL_NAME_PT100 | APP_CONFIG_PROTOCOL_NAME_JT808)
#define APP_CONFIG_PROTOCOL_NAME_CURRENT APP_CONFIG_PROTOCOL_NAME_ALL

#endif
