#ifndef __WT_BUILD_H__
#define __WT_BUILD_H__
#define WT_BUILD_NUMBER 167
#define WT_BUILD_YEAR_4 2
#define WT_BUILD_YEAR_3 0
#define WT_BUILD_YEAR_2 2
#define WT_BUILD_YEAR_1 4
#define WT_BUILD_MONTH_2 0
#define WT_BUILD_MONTH_1 9
#define WT_BUILD_DAY_2 0
#define WT_BUILD_DAY_1 6
#define WT_BUILD_HOUR_2 1
#define WT_BUILD_HOUR_1 7
#define WT_BUILD_MINUTE_2 2
#define WT_BUILD_MINUTE_1 1
#define WT_BUILD_SECOND_2 0
#define WT_BUILD_SECOND_1 4
#define WT_BUILD_MILLISECOND_3 6
#define WT_BUILD_MILLISECOND_2 5
#define WT_BUILD_MILLISECOND_1 5
#endif
